"""add due date to premium payments

Revision ID: 4bd825e4ad94
Revises: 564e43253875
Create Date: 2026-08-01 00:41:25.804848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bd825e4ad94'
down_revision = '564e43253875'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('premium_payments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'due_date',
                sa.Date(),
                nullable=True
            )
        )

    # Fill existing records
    op.execute(
        """
        UPDATE premium_payments
        SET due_date = payment_date
        WHERE due_date IS NULL
        """
    )

    with op.batch_alter_table('premium_payments', schema=None) as batch_op:
        batch_op.alter_column(
            'due_date',
            nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('premium_payments', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
