"""Added policy model

Revision ID: 564e43253875
Revises: 7d68b9aa4e10
Create Date: 2026-07-29 00:14:31.425259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564e43253875'
down_revision = '7d68b9aa4e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('policy_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('policy_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
